title: "Freelance Tax Guide"
lang: en-gb
author: "CHOUAIB"
email: "zchouaib94@gmail.com"
url: "https://chouaib263.github.io"
baseurl: "/freelance-tax-guide"
theme: minima

google_site_verification: "hHZ0onPSG4nWdr_a_u4f-jo7aFvJsA2w9zz-5R-JVlI"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# SEO settings
seo:
  type: "article"
  image: "/assets/freelance-tax-cover.jpg"
  twitter: ""
  name: "CHOUAIB"

header_pages:
  - index.md
  - about.md
  - contact.md
  - faq.md
  - privacy.md
  - resources.md
  - terms.md
  - disclaimer.md
  - glossary.md
  - guide-us.md




exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
