title: "Freelancer Tax Guide"
description: "Complete guide for freelancers on how to pay taxes in the US, UK, and Canada."
lang: en-gb
author: "CHOUAIB"
email: "zchouaib94@gmail.com"
url: "https://chouaib263.github.io"
baseurl: "/"  
theme: minima

google_site_verification: "hHZ0onPSG4nWdr_a_u4f-jo7aFvJsA2w9zz-5R-JVlI"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

markdown: kramdown
highlighter: rouge

# SEO settings
seo:
  type: "article"
  image: "/assets/freelance-tax-cover.jpg"
  twitter: ""   # كتقدر تزيد الـ username ديالك إذا عندك تويتر
  name: "CHOUAIB"

# Navigation links (اختياري حسب المشروع)
header_pages:
  - index.md

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
