title: "Tax Guide for Freelancers"
description: "Freelancer Tax Guide | US, UK & Canada"
author: "CHOUAIB"
theme: minima
lang: en
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
google-site-verification: "hHZ0onPSG4nWdr_a_u4f-jo7aFvJsA2w9zz-5R-JVlI"
